// filename: Jenkinsfile
// Code Generated by Sidekick is for learning and experimentation purposes only.
pipeline {
    agent any

    options {
        timestamps()
        disableConcurrentBuilds()
    }

    environment {
        CI = 'true'
        HEADLESS = 'true'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                bat '''
                    @echo on
                    echo PATH=%PATH%
                    where node
                    where npm
                    node -v
                    npm -v
                    dir
                    if not exist package.json exit /b 1
                    if not exist package-lock.json exit /b 1
                    npm ci
                '''
            }
        }

        stage('Install Playwright Browsers') {
            steps {
                bat 'npx playwright install'
            }
        }

        stage('Run Playwright Tests') {
            steps {
                bat 'npx playwright test'
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'playwright-report/**, test-results/**', allowEmptyArchive: true
        }
    }
}
