const { test, expect } = require('@playwright/test')
const { POManager } = require('../pageObjects/POManager')
const dataset = JSON.parse(JSON.stringify(require('../testData/loginTestData.json')))

test('Valid login with standard user', async ({ browser }) => {
    const context = await browser.newContext()
    const page = await context.newPage()
    const loginPage = new LoginPage(page)
    await loginPage.gotoUrl()
    await loginPage.loginWithAssert(dataset.validUsername, dataset.password)
})

test('Login with locked out user', async ({ browser }) => {
    const context = await browser.newContext()
    const page = await context.newPage()
    const loginPage = new LoginPage(page)
    await loginPage.gotoUrl()
    await loginPage.lockedUserLogin(dataset.lockedUsername, dataset.password)
})

test('Add an item to cart', async ({ browser }) => {
    const context = await browser.newContext()
    const page = await context.newPage()
    const username = page.locator('#user-name')
    const password = page.locator('#password')
    const signIn = page.getByRole('button', { name: 'Login' })
    await page.goto('https://www.saucedemo.com/')
    await username.fill('standard_user')
    await password.fill('secret_sauce')
    await signIn.click()
    const oneSieAddToCart = await page.locator('.inventory_item_description').filter({ hasText: 'Onesie' }).getByRole('button', { name: 'Add to cart' })
    await oneSieAddToCart.click()
    const shoppingCart = await page.locator('.shopping_cart_badge')
    await expect(shoppingCart).toContainText('1')
    await shoppingCart.click()
    const addedItemName = await page.locator('.inventory_item_name')
    await expect(addedItemName).toContainText('Sauce Labs Onesie')
    const checkOutButton = page.locator('#checkout')
    await checkOutButton.click()
    const firstName = page.locator('#first-name')
    const lastName = page.locator('#last-name')
    const zipCode = page.locator('#postal-code')
    const continueButton = page.getByRole('button', { name: 'Continue' })
    await firstName.fill('Priya')
    await lastName.fill('Nidhonkar')
    await zipCode.fill('642002')
    await continueButton.click()
    const checkOutHeader = page.getByText('Checkout: Overview', { exact: true })
    await expect(checkOutHeader).toBeVisible()
})